name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Make sure this is the correct build command

      - name: Move build files
        run: |
          mkdir -p public
          mv build/* public/

      - name: Push to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f public
          git commit -m "Deploy React app to GitHub Pages" || echo "No changes to commit"
          git push origin main
